name: Test and Coverage

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'  # 使用するGoのバージョンを指定
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Run tests with coverage
      working-directory: ./go-acl
      run: |
        go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
    
    - name: Generate coverage report (text)
      working-directory: ./go-acl
      run: |
        go tool cover -func=coverage.out > coverage.txt
    
    - name: Generate coverage report (HTML)
      working-directory: ./go-acl
      run: |
        go tool cover -html=coverage.out -o coverage.html
    
    - name: Display coverage summary
      working-directory: ./go-acl
      run: |
        echo "=== Coverage Summary ==="
        go tool cover -func=coverage.out | tail -1
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          go-acl/coverage.out
          go-acl/coverage.txt
          go-acl/coverage.html
        retention-days: 30
    
    - name: Upload coverage to Codecov (optional)
      if: false  # trueにするとCodecovにアップロード
      uses: codecov/codecov-action@v3
      with:
        files: ./go-acl/coverage.out
        flags: unittests
        name: codecov-umbrellak